---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  Canary::Stability: '0'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-XS
no_index:
  directory:
    - t
    - inc
requires:
  Types::Serialiser: '0'
  common::sense: '0'
version: 3.04
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
